name: Phase 1 CI/CD Pipeline

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm install

      - name: Run unit tests
        run: npm test ./__tests__/sum.test.js

      - name: Generate Markdown documentation
        run: npm run generate-docs

      - name: Upload Markdown documentation artifact
        uses: actions/upload-artifact@v4
        with:
          name: markdown-docs
          path: docs/documentation.md

      - run: npm install
      - run: npx eslint .

      # Codacy to be implemented later with coverage tests
      # - name: Codacy Coverage Reporter
      #   uses: codacy/codacy-coverage-reporter-action@89d6c85cfafaec52c72b6c5e8b2878d33104c699
      #   with:
      #     project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
