name: Phase 1 CI/CD Pipeline

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm install

      - name: Unit Test
        run: npm test ./__tests__/sum.test.js

#codacy to be implemented with coverage tests
      # - name: Codacy Coverage Reporter
      #   uses: codacy/codacy-coverage-reporter-action@89d6c85cfafaec52c72b6c5e8b2878d33104c699
      #   with:
      #     project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
