name: CI/CD Pipeline

on: [push]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  tests:
    name: 
    runs-on: ubuntu-latest
    outputs:
      docs-exists: ${{ steps.check-docs.outputs.docs-exists }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Run Jest tests
        run: npm test 

      - name: Run ESLint
        run: npx eslint . --max-warnings=0 --config eslint.config.js

      - name: Run unit tests with coverage
        run: npm run test -- --coverage

      - name: Generate Markdown documentation
        run: npm run generate-docs

      - name: Debug coverage files location
        run: |
          echo "=== Checking coverage files after test run ==="
          ls -la docs/coverage_report/ 2>/dev/null || echo "No docs/coverage_report/ directory"
          if [ -f "docs/coverage_report/lcov.info" ]; then
            echo "✅ Found lcov.info in docs/coverage_report/"
            head -5 docs/coverage_report/lcov.info
          else
            echo "❌ lcov.info not found in expected location"
          fi

      - name: Generate Markdown documentation
        run: npm run generate-docs

      - name: Check docs folder structure
        id: check-docs
        run: |
          echo "=== Checking docs/ directory ==="
          ls -la docs/
          if [ -f "docs/index.html" ]; then
            echo "docs-exists=true" >> $GITHUB_OUTPUT
            echo "✅ docs/index.html found"
          else
            echo "docs-exists=false" >> $GITHUB_OUTPUT
            echo "❌ docs/index.html not found"
            exit 1
          fi
          
          echo "=== Checking for coverage files in docs ==="
          find docs/ -name "*.info" -o -name "lcov.info" -o -name "coverage-final.json" 2>/dev/null || echo "No coverage files in docs/"

      - name: Upload docs artifact
        uses: actions/upload-artifact@v4
        with:
          name: docs
          path: docs/
          retention-days: 1

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: docs/coverage_report/
          retention-days: 1

    deploy:
    name: Deploy coverage_report to coverage-update branch
    runs-on: ubuntu-latest
    needs: tests
    if: github.event_name == 'push' && needs.tests.outputs.docs-exists == 'true'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Download coverage artifact
        uses: actions/download-artifact@v4
        with:
          name: coverage
          path: downloaded-coverage/  

      - name: Switch to deployment branch
        run: |
          if git ls-remote --exit-code origin coverage-update; then
            echo "Branch exists, checking out..."
            git fetch origin coverage-update
            git checkout coverage-update
          else
            echo "Creating new orphan branch..."
            git checkout --orphan coverage-update
            touch .nojekyll
          fi

      - name: Ensure docs directory exists
        run: |
          mkdir -p docs/coverage_report

      - name: Copy new coverage_report content
        run: |
          cp -r downloaded-coverage/* docs/coverage_report/

      - name: Add .nojekyll file
        run: |
          touch .nojekyll

      - name: Add updated coverage_report only
        run: |
          git add docs/coverage_report .nojekyll

      - name: Commit and push updates to coverage-update branch
        run: |
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Deploy updated coverage_report from GitHub Actions - Branch: ${{ github.ref_name }} - $(date)"
            git push origin coverage-update --force
            echo "✅ Successfully deployed updated coverage_report to coverage-update branch from ${{ github.ref_name }}"
          fi

  codacy-coverage-reporter:
    name: Upload coverage report to Codacy
    runs-on: ubuntu-latest
    needs: tests
    # Run on pushes to any branch (for testing) or when merging to main
    if: github.event_name == 'push'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run codacy-coverage-reporter
        uses: codacy/codacy-coverage-reporter-action@v1.3.0
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: docs/coverage_report/lcov.info

      - name: Download coverage artifact
        uses: actions/download-artifact@v4
        with:
          name: coverage
          path: coverage-files/

      - name: Upload coverage to Codacy
        uses: codacy/codacy-coverage-reporter-action@v1.3.0
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: coverage-files/lcov.info