name: CI/CD Pipeline

on:
  push:
    branches:
      - main

permissions:
  contents: write   # Allow push access using GITHUB_TOKEN

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm install

      - name: Run ESLint
        run: npx eslint . --max-warnings=0 --config eslint.config.js

      - name: Run unit tests with coverage
        run: npm run test -- --coverage

      - name: Generate Markdown documentation
        run: npm run generate-docs

      - name: Copy coverage HTML report to docs/
        run: |
          mkdir -p docs/coverage_report
          cp -r coverage/lcov-report/* docs/coverage_report/

      - name: Commit and push docs/ to main
        shell: bash
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/
          git commit -m "Update docs and coverage [skip ci]" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:main

  codacy-coverage-reporter:
    name: Upload coverage report to Codacy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run codacy-coverage-reporter
        uses: codacy/codacy-coverage-reporter-action@v1.3.0
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: coverage/lcov.info
