name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Install Dependencies
        run: npm install
      
      - name: Run ESLint
        run: npx eslint . --max-warnings=0 --config eslint.config.js
      
      - name: Run unit tests with coverage
        run: npm run test -- --coverage
      
      - name: Generate Markdown documentation
        run: npm run generate-docs
      
      - name: Prepare docs for GitHub Pages deployment
        run: |
          echo "=== Current branch: ${{ github.ref_name }} ==="
          echo "=== Checking docs directory structure ==="
          ls -la docs/
          
          # Check if index.html exists in docs/
          if [ -f "docs/index.html" ]; then
            echo "✅ Found index.html in docs/"
            echo "File size: $(stat -c%s docs/index.html) bytes"
          else
            echo "❌ No index.html in docs/"
            echo "Available files in docs/:"
            find docs/ -name "*.html" | head -10
            exit 1
          fi
          
          # Create .nojekyll to disable Jekyll processing
          touch docs/.nojekyll
          echo "✅ Created .nojekyll file"
          
          # Final verification
          echo "=== Files to be deployed from docs/ ==="
          ls -la docs/
      
      - name: Deploy to GitHub Pages
        if: github.event_name == 'push'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          publish_branch: gh-pages
          force_orphan: true
      
      - name: Upload coverage to Codacy
        if: github.event_name == 'push'
        uses: codacy/codacy-coverage-reporter-action@v1.3.0
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: ./docs/coverage_report/lcov.info