name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  tests:
    name: tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm install

      - name: Run ESLint
        run: npx eslint . --max-warnings=0 --config eslint.config.js

      - name: Run unit tests with coverage
        run: npm run test -- --coverage

      - name: Generate Markdown documentation
        run: npm run generate-docs

      - name: Check docs folder structure
        run: |
          echo "=== Checking docs/ directory ==="
          ls -la docs/
          if [ -f "docs/index.html" ]; then
            echo "✅ Found docs/index.html"
          else
            echo "❌ No docs/index.html found!"
            exit 1
          fi

  deploy:
    name: Deploy docs to coverage-update branch
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required for pushing branches

      - name: Setup Git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Prepare docs for deployment
        run: |
          ls -la docs/
          touch docs/.nojekyll

      - name: Switch to deployment branch
        run: |
          if git ls-remote --exit-code origin coverage-update; then
            git checkout coverage-update
          else
            git checkout --orphan coverage-update
            git rm -rf .
            git clean -fdx
          fi

      - name: Clean branch and copy docs
        run: |
          git rm -rf .
          cp -r docs/* .
          git add .

      - name: Commit and push docs to coverage-update branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Deploy docs from GitHub Actions"
            git push origin coverage-update --force
          fi

  codacy-coverage-reporter:
    name: Upload coverage report to Codacy
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Debug lcov file
        run: find . -name lcov.info

      - name: Upload coverage to Codacy
        uses: codacy/codacy-coverage-reporter-action@v1.3.0
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: ./docs/coverage_report/lcov.info  # Update path if needed
